@echo off
chcp 65001 > nul
cls
echo.
echo ESTE SCRIPT SERVE PARA RENOMEAR OS COMPUTADORES.
echo.
echo NA TELA A SEGUIR, CASO QUEIRA RENOMEAR O COMPUTADOR TECLE "S" E ENTÃO "ENTER",
echo CASO CONTRÁRIO TECLE "N" OU QUALQUER TECLA.
echo.
echo QUANDO SOLICITADO INSIRA O PREFIXO DO NOME DO COMPUTADOR (ANTES DO "-"), SENDO ELE FORMADO PELA
echo LETRA "D" PARA DESKTOP E "N" PARA NOTEBOOK SEGUIDO DO NUMERO DE TRÊS DÍGITOS
echo CORRESPONDENTE A VLAN OU CÓDIGO DO LOCAL CONFORME TABELA QUE SERÁ ABERTA A SEGUIR.
echo.
echo O NOME DO COMPUTADOR AO FINAL FICARÁ COM O SEGUINTE PADRÃO: 
echo D001-00AA00 (D=DESKTOP, 001=VLAN 001, 00AA00=SEIS ÚLTIMOS DÍGITOS DO MAC)
echo.
echo EM CADA TELA E NECESSÁRIO AUTORIZAR O SCRIPT EXECUTAR. 
echo QUANDO PEDIDO APERTANDO AS TECLAS "R" E "ENTER" AO RECEBER A MENSAGEM DE ALERTA.
echo.
pause
cls
start "" cmd /c "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" LINK_PARA_PLANILHA_COM_A_LISTA_DE_PADROES_DE_NOMES
powershell -Command "Set-ExecutionPolicy Unrestricted -Scope CurrentUser;./processa.PS1"
exit
